#!/bin/sh -

sym_file="$1"
api_file="$2"
tmp_file="${api_file}.tmp"
api_file_ub=`basename ${api_file} | tr '.-' '_'`

rm -f "$tmp_file"

cat << _EOF > "$tmp_file"
;
; DO NOT EDIT!!  This file is automatically generated from ${sym_file}.
;
; Copyright (c) 2023, 2024 Jason R. Thorpe.
; All rights reserved.
;
; Redistribution and use in source and binary forms, with or without
; modification, are permitted provided that the following conditions
; are met:
; 1. Redistributions of source code must retain the above copyright
;    notice, this list of conditions and the following disclaimer.
; 2. Redistributions in binary form must reproduce the above copyright
;    notice, this list of conditions and the following disclaimer in the
;    documentation and/or other materials provided with the distribution.
;
; THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
; IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
; OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
; IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
; INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
; BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
; AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
; OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
; OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
; SUCH DAMAGE.
;
_EOF

SysData_list=`grep "^XSysData_" "$sym_file" | cut -f 1`
SysSubr_list=`grep "^XSysSubr_" "$sym_file" | cut -f 1`
SysAddr_list=`grep "^XSysAddr_" "$sym_file" | cut -f 1 | grep -v _size`

cat << _EOF >> "$tmp_file"

	if	${api_file_ub}_included
	else
${api_file_ub}_included	equ	1

;
; System Subroutines.  These are called indirectly via a jump table in
; the fixed ROM.  These are meant as something between library routines
; and system calls.
;
; Invoke them like so:
;
;	jsr	[SysSubr_whatever]
;
_EOF
(for xsubr_name in $SysSubr_list; do
	subr_val=`grep "^${xsubr_name}\t" "$sym_file" | cut -f 3`
	subr_name=`echo ${xsubr_name} | sed 's,^X,,'`
	if [ x"$subr_name" != x ]; then
		echo "$subr_name equ $subr_val"
	fi
done) | sort >> "$tmp_file"

cat << _EOF >> "$tmp_file"

;
; System Data linkage.  These are indirect references to data exported
; by the fixed ROM.
;
; Retrieve the actual address like so:
;
;	ldx	SysData_fs_avail
;
_EOF

(for xdata_name in $SysData_list; do
	data_val=`grep "^${xdata_name}\t" "$sym_file" | cut -f 3`
	data_name=`echo ${xdata_name} | sed 's,^X,,'`
	if [ x"$data_name" != x ]; then
		echo "$data_name equ $data_val"
	fi
done) | sort >> "$tmp_file"

cat << _EOF >> "$tmp_file"

;
; System Addresses.  These are the region addresses (and corresponding
; region sizes) that are exported to programs.  All other address regions
; should be considered reserved to the operating system.
;
_EOF
(for xaddr_name in $SysAddr_list; do
	addr_val=`grep "^${xaddr_name}\t" "$sym_file" | cut -f 3`
	size_val=`grep "^${xaddr_name}_size" "$sym_file" | cut -f 3`
	addr_name=`echo ${xaddr_name} | sed 's,^X,,'`
	echo "${addr_name} equ ${addr_val}"
	echo "${addr_name}_size equ ${size_val}"
done) | sort >> "$tmp_file"

cat << _EOF >> "$tmp_file"

	endif	; ${api_file_ub}_included
_EOF

mv "$tmp_file" "$api_file"
